### ISSUE TITLE
Crana website + Documentation

### ISSUE THREAD

**Issue by pankaryp** [CranaJS/crana#14]
Hello there, 

I really loved the idea of Crana and i want to contribute as much as i can. I believe that the most funtumental thing about a project is how you present it to the public. 

So what do you think about developing a simple website with documentation, maybe with docsify, docusaurous, docz or a similar framework-generator or even a custom made minimalistic site?

Comment your thoughts. I would love to help make this project bigger =)

**Comment by scriptify** [comment]
Hi Panagiotis!
First of all thanks for your kind words and thanks for your willingness to be part of this project!

You are totally right, the presentation to the public is very very important, and there are many things to do regarding this aspect. I've recently set up a Kanban board under "projects" (https://github.com/scriptify/crana/projects/1), and there actually is excatly such a todo!

I am currently working on the next big change of Crana: Extensions (you can read more about them on the Kanban board). Therefore, I will not have so much time for documentation etc, so it would be awesome if you would like to start creating it! I can give you any help you need: Guiding you through the project, explaining stuff, answering questions, ... 🙂 

Honestly I have no experience in creating documentation websites, until now I've always used SSG like GatsbyJS to create simple websites.

I also think that the README would need a lot of improvement, so that it's clearer what Crana is exactly about and what problems it tries to solve.

So which steps should we take next regarding the documentation/presentation to the public, what do you think?

**Comment by pankaryp** [comment]
I am gonna install Crana and test some stuff in the next couple of days, to get a better grip on the project and be able to improve the README.md and the documentation in general. And i will create a pull request with my suggestions. 
In the meantime, check this out, https://docsify.js.org/#/?id=docsify . This kind of minimal site i am talking about. It's pretty straight forward and i think the minimal design which is implemented is absolutely smooth for open source projects.

**Comment by scriptify** [comment]
I think docsify looks great, we could use it for the documentation of Crana.

**Comment by pankaryp** [comment]
Hello again, 

I am in the verge of finishing a first prototype of crana's documentation site. 

I think that maybe you should create an organization named Crana and trasfer the main repository there. Crana needs to be an organization in order to create multiple repositories like crana-core, crana-website, crana-express extension for example etc etc. 
The reason i am suggesting this, is because i will have to upload Crana's documentation code somewhere and its very convient to create an organization.

**Comment by pankaryp** [comment]
You can see a prototype of the Docs here: http://crana-doc-test.surge.sh/#/. Of course it needs a lot of work, but this is the style it will be built upon.

**Comment by scriptify** [comment]
That's a very good idea, I've just created an organization and sent you an invitation. I like how the documentation looks so far, good work!

**Comment by scriptify** [comment]
@pankaryp I've just uploaded a new release of crana with the tag "next" to npm. You can try it by installing crana like this: "npm i -g crana@next" (what you probably already know ^^). It is the version you can find at this branch: https://github.com/CranaJS/crana/tree/feature/extensions

Here, I implemented crana extensions. You can already choose  between 3 offical extensions I've included (all of them under "official-extensions"): React, Typescript, Svelte. When you run "crana init <projectName>", you can choose which extensions to install. I think there's a lot left to explain, but I'm in a bit of a hurry right now, so I'll not explain everything in this comment. Please just drop your questions! (I'll come back here ASAP). PS: The implementation of the extension system also means that Crana is now totally independent of React, yei! 😄

**Comment by scriptify** [comment]
So I'd suggest to publish the official docs page as soon as extensions have been shipped and documented.

**Comment by pankaryp** [comment]
Awesome, i will check it out as soon as i return home and i will finish the docs in the next 2-3 days. Didnt have much time to contribute this week unfortunately.

**Comment by scriptify** [comment]
There are still a few things to stabilize and test before the next version can ship, so we have time. I also struggle to find more time, but that's a developer's life ^^

**Comment by pankaryp** [comment]
hehehe yea me too cause i have tones of university projects and right now i had an idea also for a CLI, that takes cares the project set up in different languages (javascript, nim, rust, elixir, python etc). So on top of all , i am working on this. Life is awesome! Lol

**Comment by pankaryp** [comment]
Btw if you need any help with the development of a plugin or maybe to extend crana's core, let me know. I am looking forward into getting more into crana's code.

**Comment by scriptify** [comment]
Yea I also have a lot of projects going on, but this is the only OS project I can currently afford. But I would love to see it grow and become more mature from commit to commit.

Yea that would be awesome! I can guide you through the code if you want, we could have a video call with screen sharing, I think that would be the mose effective way.

**Comment by pankaryp** [comment]
yeap sure!! We can arrange that. Tell me if u have time inside this weekend !?

**Comment by scriptify** [comment]
During the weekend I have no time unfortunately, not until Tuesday TBH. I'd have time from now until Friday night all the time basically.
